services:
  - redis-server

language: php
php:
  - 7.0

env:
  - SYMFONY_VERSION=2.8.*

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

install:
  - bash -c 'echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini'

before_script:
  - travis_retry composer self-update
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
