sudo: false
language: php

php:
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*@dev

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache

services:
  - redis-server

install:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi'
  - composer self-update

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source
  - composer update --prefer-source

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
