parameters:
  tree_house.io.worker.listener.source_modification.class: TreeHouse\IoBundle\Bridge\WorkerBundle\EventListener\SourceModificationListener
  tree_house.io.worker.listener.import_schedule.class: TreeHouse\IoBundle\Bridge\WorkerBundle\EventListener\ImportScheduleListener
  tree_house.io.worker.listener.scrape_url.class: TreeHouse\IoBundle\Bridge\WorkerBundle\EventListener\ScrapeUrlListener
  tree_house.io.worker.listener.scrape_source.class: TreeHouse\IoBundle\Bridge\WorkerBundle\EventListener\ScrapeSourceListener
  tree_house.io.worker.listener.rate_limit.class: TreeHouse\IoBundle\Bridge\WorkerBundle\EventListener\ScrapeRateLimitListener
  tree_house.io.queue.executor.import_schedule.class: TreeHouse\IoBundle\Bridge\WorkerBundle\Executor\ImportScheduleExecutor
  tree_house.io.queue.executor.export_item.class: TreeHouse\IoBundle\Bridge\WorkerBundle\Executor\ItemExportExecutor
  tree_house.io.queue.executor.export_item_remove.class: TreeHouse\IoBundle\Bridge\WorkerBundle\Executor\ItemExportRemoveExecutor
  tree_house.io.queue.executor.import_part.class: TreeHouse\IoBundle\Bridge\WorkerBundle\Executor\ImportPartExecutor
  tree_house.io.queue.executor.scrape_url.class: TreeHouse\IoBundle\Bridge\WorkerBundle\Executor\ScrapeUrlExecutor
  tree_house.io.queue.executor.scrape_source_revisit.class: TreeHouse\IoBundle\Bridge\WorkerBundle\Executor\ScrapeRevisitSourceExecutor
  tree_house.io.queue.executor.source_process.class: TreeHouse\IoBundle\Bridge\WorkerBundle\Executor\SourceProcessExecutor

services:
  tree_house.io.worker.listener.source_modification:
    class: %tree_house.io.worker.listener.source_modification.class%
    arguments:
      - @tree_house.worker.queue_manager
    tags:
      - { name: tree_house.io.event_listener, event: io.source.process, method: onSourceProcess }

  tree_house.io.worker.listener.import_schedule:
    class: %tree_house.io.worker.listener.import_schedule.class%
    arguments:
      - @tree_house.worker.queue_manager
      - %tree_house.io.worker.import.import_part.time_to_run%
    tags:
      - { name: tree_house.io.event_listener, event: io.import.part.scheduled, method: onPartScheduled }

  tree_house.io.worker.listener.scrape_url:
    class: %tree_house.io.worker.listener.scrape_url.class%
    arguments:
      - @tree_house.worker.queue_manager
    tags:
      - { name: tree_house.io.event_listener, event: io.scrape.url.next, method: onScrapeNextUrl }

  tree_house.io.worker.listener.scrape_source:
    class: %tree_house.io.worker.listener.scrape_source.class%
    arguments:
      - @tree_house.worker.queue_manager
    tags:
      - { name: tree_house.io.event_listener, event: io.scrape.source.revisit, method: onScrapeRevisitSource }

  tree_house.io.worker.executor.export_item:
    class: %tree_house.io.queue.executor.export_item.class%
    arguments:
      - @tree_house.io.export.feed_exporter
      - @doctrine
    tags:
      - { name: tree_house.worker.executor }

  tree_house.io.worker.executor.export_item_remove:
    class: %tree_house.io.queue.executor.export_item_remove.class%
    arguments:
      - @tree_house.io.export.feed_exporter
      - @doctrine
    tags:
      - { name: tree_house.worker.executor }

  tree_house.io.worker.executor.import_part:
    class: %tree_house.io.queue.executor.import_part.class%
    arguments:
      - @doctrine
      - @tree_house.io.import.import_factory
      - @logger
    tags:
      - { name: tree_house.worker.executor }

  tree_house.io.worker.executor.import_schedule:
    class: %tree_house.io.queue.executor.import_schedule.class%
    arguments:
      - @tree_house.io.import.import_scheduler
      - @tree_house.io.import.import_factory
      - @logger
    tags:
      - { name: tree_house.worker.executor }

  tree_house.io.worker.executor.scrape_url:
    class: %tree_house.io.queue.executor.scrape_url.class%
    arguments:
      - @doctrine
      - @tree_house.io.scrape.scraper_factory
      - @logger
    tags:
      - { name: tree_house.worker.executor }

  tree_house.io.worker.executor.scrape_source_revisit:
    class: %tree_house.io.queue.executor.scrape_source_revisit.class%
    arguments:
      - @tree_house.io.source_manager
      - @tree_house.io.scrape.source.revisitor
      - @logger
    tags:
      - { name: tree_house.worker.executor }

  tree_house.io.worker.executor.source_process:
    class: %tree_house.io.queue.executor.source_process.class%
    arguments:
      - @tree_house.io.source_manager
      - @tree_house.io.source_processor
      - @logger
    tags:
      - { name: tree_house.worker.executor }
      - { name: monolog.logger, channel: io }
