services:
  tree_house.io.command.feed.list:
    class: TreeHouse\IoBundle\Command\FeedListCommand
    arguments:
      - @doctrine
    tags:
      - { name: console.command }

  tree_house.io.command.feed.inspect:
    class: TreeHouse\IoBundle\Command\FeedInspectCommand
    tags:
      - { name: console.command }

  tree_house.io.command.import.close:
    class: TreeHouse\IoBundle\Command\ImportCloseCommand
    arguments:
      - @doctrine
    tags:
      - { name: console.command }

  tree_house.io.command.import.run:
    class: TreeHouse\IoBundle\Command\ImportRunCommand
    arguments:
      - @doctrine
      - @tree_house.io.import.import_factory
      - @logger
    tags:
      - { name: console.command }

  tree_house.io.command.import.part:
    class: TreeHouse\IoBundle\Command\ImportPartCommand
    arguments:
      - @doctrine
      - @tree_house.io.import.import_factory
      - @logger
    tags:
      - { name: console.command }

  tree_house.io.command.import.schedule:
    class: TreeHouse\IoBundle\Command\ImportScheduleCommand
    arguments:
      - @tree_house.io.import.import_factory
      - @tree_house.io.import.import_scheduler
    tags:
      - { name: console.command }

  tree_house.io.command.import.reschedule:
    class: TreeHouse\IoBundle\Command\ImportRescheduleCommand
    arguments:
      - @tree_house.io.import.import_scheduler
      - @tree_house.io.import.processor.posix
    tags:
      - { name: console.command }

  tree_house.io.command.import.rotate:
    class: TreeHouse\IoBundle\Command\ImportRotateCommand
    arguments:
      - @doctrine
      - @tree_house.io.import.import_rotator
    tags:
      - { name: console.command }

  tree_house.io.command.import.cleanup:
    class: TreeHouse\IoBundle\Command\ImportCleanupCommand
    arguments:
      - @doctrine
      - @tree_house.io.import.import_rotator
    tags:
      - { name: console.command }

  tree_house.io.command.export.create:
    class: TreeHouse\IoBundle\Command\ExportCreateCommand
    arguments:
      - @tree_house.io.export.feed_exporter
    tags:
      - { name: console.command }

  tree_house.io.command.export.cache_clear:
    class: TreeHouse\IoBundle\Command\ExportCacheClearCommand
    arguments:
      - @tree_house.io.export.feed_exporter
    tags:
      - { name: console.command }

  tree_house.io.command.export.inspect:
    class: TreeHouse\IoBundle\Command\ExportInspectCommand
    arguments:
      - @tree_house.io.export.feed_exporter
    tags:
      - { name: console.command }

  tree_house.io.command.export.validate:
    class: TreeHouse\IoBundle\Command\ExportValidateCommand
    arguments:
      - @tree_house.io.export.feed_exporter

  tree_house.io.command.scrape.url:
    class: TreeHouse\IoBundle\Command\ScrapeUrlCommand
    arguments:
      - @doctrine
      - @tree_house.io.scrape.scraper_factory
    tags:
      - { name: console.command }

  tree_house.io.command.scrape.start:
    class: TreeHouse\IoBundle\Command\ScrapeStartCommand
    arguments:
      - @doctrine
      - @tree_house.io.scrape.scraper_factory
    tags:
      - { name: console.command }

  tree_house.io.command.scrape.revisit:
    class: TreeHouse\IoBundle\Command\ScrapeRevisitCommand
    arguments:
      - @doctrine
      - @tree_house.io.source_manager
      - @tree_house.io.scrape.source.revisitor
    tags:
      - { name: console.command }

  tree_house.io.command.crawler.log:
    class: TreeHouse\IoBundle\Command\CrawlerLogCommand
    arguments:
      - @tree_house.io.scrape.scraper_factory
    tags:
      - { name: console.command }

  tree_house.io.command.source.process:
    class: TreeHouse\IoBundle\Command\SourceProcessCommand
    arguments:
      - @tree_house.io.source_manager
      - @tree_house.io.source_processor
    tags:
      - { name: console.command }

  tree_house.io.command.source.cleanup:
    class: TreeHouse\IoBundle\Command\SourceCleanupCommand
    arguments:
      - @tree_house.io.source_cleaner
      - @tree_house.io.origin_manager
      - @logger
    tags:
      - { name: console.command }
