parameters:
  tree_house.io.export.feed_exporter.class: TreeHouse\IoBundle\Export\FeedExporter
  tree_house.io.export.feed_writer.class: TreeHouse\IoBundle\Export\FeedWriter

services:
  tree_house.io.export.feed_exporter:
    class: %tree_house.io.export.feed_exporter.class%
    arguments:
      - %tree_house.io.export.cache_dir%
      - %tree_house.io.export.output_dir%
      - @tree_house.io.export.feed_writer
      - @filesystem
      - @event_dispatcher

  tree_house.io.export.feed_writer:
    class: %tree_house.io.export.feed_writer.class%
    arguments:
      - @templating
