services:
  tree_house.io.export.feed_exporter:
    public: true
    class: TreeHouse\IoBundle\Export\FeedExporter
    arguments:
      - %tree_house.io.export.cache_dir%
      - %tree_house.io.export.output_dir%
      - @tree_house.io.export.feed_writer_factory
      - @filesystem
      - @event_dispatcher

  tree_house.io.export.feed_writer_factory:
    public: false
    class: TreeHouse\IoBundle\Export\FeedWriterFactory
    arguments:
      - @templating
