parameters:
  tree_house.io.import.dir: %tree_house.io.data_dir%/import
  tree_house.io.import.reader.multipart.default_part_size: 1000
  tree_house.io.import.item_logger.array.class: TreeHouse\IoBundle\Import\Log\ArrayItemLogger
  tree_house.io.import.item_logger.redis.class: TreeHouse\IoBundle\Import\Log\RedisItemLogger
  tree_house.io.import.item_logger.predis.class: TreeHouse\IoBundle\Import\Log\PredisItemLogger

services:
  tree_house.io.import.listener.import_removal:
    public: true
    class: TreeHouse\IoBundle\EventListener\ImportRemovalListener
    arguments:
      - @tree_house.io.import.import_storage
      - @?tree_house.io.import.item_logger
    tags:
      - { name: doctrine.event_listener, event: preRemove, lazy: true }

  tree_house.io.import.importer_builder_factory:
    public: false
    class: TreeHouse\IoBundle\Import\Importer\ImporterBuilderFactory

  tree_house.io.import.import_storage:
    public: false
    class: TreeHouse\IoBundle\Import\ImportStorage
    arguments:
      - %tree_house.io.import.dir%

  tree_house.io.import.import_factory:
    public: false
    class: TreeHouse\IoBundle\Import\ImportFactory
    arguments:
      - @doctrine
      - @tree_house.io.import.registry
      - @tree_house.io.import.importer_builder_factory
      - @tree_house.io.import.reader_builder_factory
      - @tree_house.io.import.import_storage
      - @tree_house.io.event_dispatcher

  tree_house.io.import.reader_builder_factory:
    public: false
    class: TreeHouse\IoBundle\Import\Reader\ReaderBuilderFactory

  tree_house.io.import.feed_type:
    public: false
    class: TreeHouse\IoBundle\Import\Feed\Type\AbstractFeedType
    abstract: true
    arguments:
      - @doctrine
      - @tree_house.io.source.manager.cached

  tree_house.io.import.handler.doctrine:
    public: false
    class: TreeHouse\IoBundle\Import\Handler\DoctrineHandler
    arguments:
      - @tree_house.io.source.manager.cached
      - @validator
    tags:
      - { name: tree_house.io.import_handler, alias: doctrine }

  tree_house.io.import.importer_type.default:
    public: false
    class: TreeHouse\IoBundle\Import\Importer\Type\DefaultImporterType
    tags:
      - { name: tree_house.io.importer_type, alias: default }

  tree_house.io.import.reader_type.xml:
    public: false
    class: TreeHouse\IoBundle\Import\Reader\Type\XmlReaderType
    tags:
      - { name: tree_house.io.reader_type, alias: xml }

  tree_house.io.import.reader_type.xml_multi_part:
    public: false
    class: TreeHouse\IoBundle\Import\Reader\Type\XmlMultiPartReaderType
    calls:
      - [setDefaultPartSize, [%tree_house.io.import.reader.multipart.default_part_size%]]
    tags:
      - { name: tree_house.io.reader_type, alias: xml_multi_part }

  tree_house.io.import.processor.posix:
    public: false
    class: TreeHouse\IoBundle\Import\Processor\PosixProcessor
    tags:
      - { name: tree_house.io.import_processor, alias: posix }

  tree_house.io.import.registry:
    public: true
    class: TreeHouse\IoBundle\Import\ImportRegistry

  tree_house.io.import.import_scheduler:
    public: false
    class: TreeHouse\IoBundle\Import\ImportScheduler
    arguments:
      - @doctrine
      - @tree_house.io.import.import_factory
      - @tree_house.io.event_dispatcher

  tree_house.io.import.import_rotator:
    public: false
    class: TreeHouse\IoBundle\Import\ImportRotator
    arguments:
      - @doctrine
      - @tree_house.io.event_dispatcher
