parameters:
  tree_house.io.scrape.crawler.abstract.class: TreeHouse\IoBundle\Scrape\Crawler\AbstractCrawler
  tree_house.io.scrape.crawler.client.guzzle_client.class: GuzzleHttp\Client
  tree_house.io.scrape.crawler.client.guzzle.class: TreeHouse\IoBundle\Scrape\Crawler\Client\GuzzleClient
  tree_house.io.scrape.scraper_factory.class: TreeHouse\IoBundle\Scrape\ScraperFactory
  tree_house.io.scrape.handler.doctrine.class: TreeHouse\IoBundle\Scrape\Handler\DoctrineHandler
  tree_house.io.scrape.parser_type.abstract.class: TreeHouse\IoBundle\Scrape\Parser\Type\AbstractParserType

services:
  tree_house.io.scrape.scraper_factory:
    class: %tree_house.io.scrape.scraper_factory.class%
    arguments:
      - @tree_house.io.event_dispatcher

  tree_house.io.scrape.crawler.client.guzzle_client:
    public: false
    class: %tree_house.io.scrape.crawler.client.guzzle_client.class%
    arguments:
      defaults:
        timeout: 20
        connect_timeout: 5

  tree_house.io.scrape.crawler.client.guzzle:
    public: false
    class: %tree_house.io.scrape.crawler.client.guzzle.class%
    arguments:
      - @tree_house.io.scrape.crawler.client.guzzle_client
    calls:
      - ['setLogger', [@logger]]

  tree_house.io.scrape.crawler.abstract:
    abstract: true
    class: %tree_house.io.scrape.crawler.abstract.class%
    tags:
      - { name: monolog.logger, channel: io }

  tree_house.io.scrape.handler.doctrine:
    public: false
    class: %tree_house.io.scrape.handler.doctrine.class%
    arguments:
      - @tree_house.io.source.manager.import
      - @validator
    tags:
      - { name: tree_house.io.scrape.handler, alias: doctrine }

  tree_house.io.scrape.parser_type.abstract:
    abstract: true
    class: %tree_house.io.scrape.parser_type.abstract.class%
    arguments:
      - @doctrine
      - @tree_house.io.source.manager.import
