services:
  tree_house.io.scrape.scraper_factory:
    public: false
    class: TreeHouse\IoBundle\Scrape\ScraperFactory
    arguments:
      - @tree_house.io.event_dispatcher

  tree_house.io.scrape.crawler.client.guzzle_client:
    public: false
    class: GuzzleHttp\Client
    arguments:
      defaults:
        timeout: 20
        connect_timeout: 5

  tree_house.io.scrape.crawler.client.guzzle:
    public: false
    class: TreeHouse\IoBundle\Scrape\Crawler\Client\GuzzleClient
    arguments:
      - @tree_house.io.scrape.crawler.client.guzzle_client
    calls:
      - ['setLogger', [@logger]]
    tags:
      - { name: monolog.logger, channel: io }

  tree_house.io.scrape.crawler.abstract:
    abstract: true
    public: false
    class: TreeHouse\IoBundle\Scrape\Crawler\AbstractCrawler
    tags:
      - { name: monolog.logger, channel: io }

  tree_house.io.scrape.handler.doctrine:
    public: false
    class: TreeHouse\IoBundle\Scrape\Handler\DoctrineHandler
    arguments:
      - @tree_house.io.source.manager.cached
      - @validator
    tags:
      - { name: tree_house.io.scrape.handler, alias: doctrine }

  tree_house.io.scrape.parser_type.abstract:
    abstract: true
    public: false
    class: TreeHouse\IoBundle\Scrape\Parser\Type\AbstractParserType
    arguments:
      - @doctrine
      - @tree_house.io.source.manager.cached

  tree_house.io.scrape.source.revisitor:
    public: false
    class: TreeHouse\IoBundle\Scrape\SourceRevisitor
    arguments:
      - @tree_house.io.source_manager
      - @tree_house.io.scrape.scraper_factory
