parameters:
  tree_house.io.event_dispatcher.class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
  tree_house.io.listener.source_modification.class: TreeHouse\IoBundle\EventListener\SourceModificationListener
  tree_house.io.twig.extension.common.class: TreeHouse\IoBundle\Twig\CommonExtension

services:
  tree_house.io.event_dispatcher:
    class: %tree_house.io.event_dispatcher.class%
    arguments:
      - @service_container

  tree_house.io.listener.source_modification:
    class: %tree_house.io.listener.source_modification.class%
    arguments:
      - @tree_house.io.source_processor
      - @tree_house.io.event_dispatcher
    tags:
      - { name: doctrine.event_listener, event: onFlush, lazy: true }
      - { name: doctrine.event_listener, event: postFlush, lazy: true }

  tree_house.io.twig.extension.common:
    class: %tree_house.io.twig.extension.common.class%
    tags:
      - { name: twig.extension }
