parameters:
  tree_house.io.source.manager.cached.class:
  tree_house.io.source.cleaner.delegating.class:
  tree_house.io.source.cleaner.orphaned.class:
  tree_house.io.source.cleaner.idle.class:
  tree_house.io.source.processor.delegating.class:

services:
  tree_house.io.source.manager.cached:
    public: false
    class: TreeHouse\IoBundle\Source\Manager\CachedSourceManager
    arguments:
      - @tree_house.io.source_manager

  tree_house.io.source.cleaner.delegating:
    public: false
    class: TreeHouse\IoBundle\Source\Cleaner\DelegatingSourceCleaner
    arguments:
      - @tree_house.io.source_manager
      - @tree_house.io.event_dispatcher

  tree_house.io.source.cleaner.orphaned:
    public: false
    class: TreeHouse\IoBundle\Source\Cleaner\OrphanedSourceCleaner
    arguments:
      - @tree_house.io.source_manager
    tags:
      - { name: tree_house.io.source_cleaner }

  tree_house.io.source.cleaner.idle:
    public: false
    class: TreeHouse\IoBundle\Source\Cleaner\IdleSourceCleaner
    arguments:
      - @doctrine
      - @tree_house.io.source_manager
      - @tree_house.io.event_dispatcher
      - @logger
    tags:
      - { name: tree_house.io.source_cleaner }
      - { name: monolog.logger, channel: io }

  tree_house.io.source.processor.delegating:
    public: false
    class: TreeHouse\IoBundle\Source\Processor\DelegatingSourceProcessor
