parameters:
  tree_house.io.source.manager.import.class: TreeHouse\IoBundle\Source\Manager\ImportSourceManager
  tree_house.io.source.cleaner.delegating.class: TreeHouse\IoBundle\Source\Cleaner\DelegatingSourceCleaner
  tree_house.io.source.cleaner.orphaned.class: TreeHouse\IoBundle\Source\Cleaner\OrphanedSourceCleaner
  tree_house.io.source.cleaner.idle.class: TreeHouse\IoBundle\Source\Cleaner\IdleSourceCleaner
  tree_house.io.source.processor.delegating.class: TreeHouse\IoBundle\Source\Processor\DelegatingSourceProcessor

services:
  tree_house.io.source.manager.import:
    class: %tree_house.io.source.manager.import.class%
    arguments:
      - @tree_house.io.source_manager

  tree_house.io.source.cleaner.delegating:
    class: %tree_house.io.source.cleaner.delegating.class%
    arguments:
      - @tree_house.io.source_manager
      - @tree_house.io.event_dispatcher

  tree_house.io.source.cleaner.orphaned:
    class: %tree_house.io.source.cleaner.orphaned.class%
    arguments:
      - @tree_house.io.source_manager
    tags:
      - { name: tree_house.io.source_cleaner }

  tree_house.io.source.cleaner.idle:
    class: %tree_house.io.source.cleaner.idle.class%
    arguments:
      - @doctrine
      - @tree_house.io.source_manager
      - @tree_house.io.event_dispatcher
      - @logger
    tags:
      - { name: tree_house.io.source_cleaner }

  tree_house.io.source.processor.delegating:
    class: %tree_house.io.source.processor.delegating.class%
